- name: Enable IP forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes
- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present
- name: Create containerd config dir
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0644'
- name: Copy containerd config
  ansible.builtin.copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644' 
- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - containerd
      - curl
      - gpg
      - apt-transport-https
    state: present
- name: Download Kubernetes gpg key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
    dest: /tmp/Release.key
    mode: '0440'
- name: Dearmor Kubernetes gpg key
  ansible.builtin.command:
    chdir: /tmp
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg Release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
- name: Add Kubernetes APT source list
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /\n"
    owner: root
    group: root
    mode: '0644'
- name: Install Kubernetes packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present
